Fix two memory leak issues
thewakingsands/OverlayPlugin pull request #2
Opened 2021-10-06 09:44 UTC by sandtechnology

Leak1: Since not consumer (ImportedLogLinesEvent Subscriber) there, the imported logs will persist in memory
Leak2: Since the overlay was disabled, the script (for example, the log line when combating) added to `scriptQueue` will never be executed unless enable it again.

2021-10-08 03:36 UTC, sandtechnology commented
@oott123 三三有时间的话可以也看看这个pr吗（

2021-10-08 05:17 UTC, oott123 requested changes

2021-10-08 05:17 UTC, oott123 commented on HtmlRenderer/Renderer.cs
> +        private bool isStopRender = true;
Should be `_isStopRender` to match other private variables, and IMO `_isRendererStopped` is a better name

2021-10-08 05:17 UTC, oott123 commented on OverlayPlugin.Core/EventSources/MiniParseEventSource.cs
> -            if (importing && HasSubscriber(ImportedLogLinesEvent))
Why remove `importing` here ?

2021-10-08 05:17 UTC, oott123 commented on OverlayPlugin.Core/EventSources/MiniParseEventSource.cs
> +                        DispatchEvent(JObject.FromObject(new
Move DispatchEvent into the lock context can cause `importedLogs` lock be taken until event dispatched. Is this intended?

2021-10-08 05:21 UTC, oott123 commented on HtmlRenderer/Renderer.cs
> +            EndRender();
`EndRender()` here sets `isStopRender` to true, what if event comes in before it setted to false?

I think we should use something more solid.

2021-10-08 05:22 UTC, oott123 commented
感觉用这种临时变量来确定它是否被禁用了不是很科学，万一事件在你一次渲染中间来了就很烦。

还是要想办法读是否被禁用的设置比较合理。

2021-10-08 14:00 UTC, sandtechnology commented on OverlayPlugin.Core/EventSources/MiniParseEventSource.cs
> -            if (importing && HasSubscriber(ImportedLogLinesEvent))
如果检查了`importing`的状态 那么直到下一次导入日志前都会有上次剩下的没有dispatched的日志行 所以在这里移除了 实时进行发送

2021-10-08 14:01 UTC, sandtechnology commented on OverlayPlugin.Core/EventSources/MiniParseEventSource.cs
> +                        DispatchEvent(JObject.FromObject(new
哦 这不是预期情况 会进行修改

2021-10-08 14:23 UTC, sandtechnology commented on HtmlRenderer/Renderer.cs
> +        private bool isStopRender = true;
更名为 `_isRendering` 了，感觉更加合适

2021-10-08 14:48 UTC, sandtechnology commented
> 
> 
> 感觉用这种临时变量来确定它是否被禁用了不是很科学，万一事件在你一次渲染中间来了就很烦。
> 
> 还是要想办法读是否被禁用的设置比较合理。

这边`Render`里面的逻辑是 如果没有在渲染的话就不会接收新的脚本 我觉得没啥问题（
关于Corner case的问题 这里对结束渲染时的情况做了一下考虑 对脚本列表进行了清空 如果是在开始渲染时的话 不会进行脚本接收

2021-10-09 01:16 UTC, oott123 approved these changes
LGTM

2021-10-09 01:18 UTC, merged