Add lock for memory processors, fix concurrent issue
thewakingsands/OverlayPlugin pull request #3
Opened 2021-10-16 11:32 UTC by sandtechnology

因为对C#的锁不熟，姑且用了lock语句和 `_mutex` 变量来管理 `processHandle` 和 `process` 变量的锁，如果有建议欢迎提出（
修复了下述截图的问题，来源ACT国服整合支持群（163386335）：
![TIM图片20211016193211](https://user-images.githubusercontent.com/20417547/137585751-aef9e3d7-6039-4dbf-8035-a0491dd60674.png)

2021-10-16 11:38 UTC, sandtechnology commented
@oott123 麻烦三三再帮忙看看这个PR，才发现没有watch这个仓库（

2021-10-17 03:15 UTC, oott123 requested changes
这个点挺好的，修改进程的时候确实应该锁住。就是锁住里面最好不要有机会调用外部函数，不然的话容易死锁或者锁到不应该锁的东西。

如果能用 RW 锁是最好了，毕竟读多写少。不过 C# 里 RW 锁怎么弄我也不太熟……

2021-10-17 03:15 UTC, oott123 commented on OverlayPlugin.Core/MemoryProcessors/FFXIVMemory.cs
> +            lock (_mutex)
You should not put `OnProgressChange event` handlers in mutex (when `process != null && process.HasExited`), which may lead to dead locks. Considering move `OnProgressChange` out of mutex.

2021-10-17 03:15 UTC, oott123 commented on OverlayPlugin.Core/MemoryProcessors/FFXIVMemory.cs
> +            lock (_mutex)
It's not good to `MessageBox.Show` in mutex because `MessageBox.Show` is a user-blocking function.

2021-10-17 03:15 UTC, oott123 commented on OverlayPlugin.Core/MemoryProcessors/FFXIVMemory.cs
> +        private readonly Object _mutex = new Object();
This vairable name should be more clear, like `processMutex` or `processLock` which I prefer more.

2021-10-17 04:23 UTC, sandtechnology commented
看了一下发现忘记对读内存上锁了，打算改成 `ReaderWriterLockSlim` 读写锁（

2021-10-17 05:13 UTC, sandtechnology commented
好了 可以Review了（

2021-10-17 14:29 UTC, oott123 approved these changes
LGTM

2021-10-17 14:31 UTC, merged